# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode11.3

env:
  - DESTINATION='platform=iOS Simulator,name=iPad Air'
  - DESTINATION='platform=iOS Simulator,OS=12.4,name=iPad Air 2'
  - DESTINATION='platform=iOS Simulator,name=iPad Pro (9.7-inch)'
  - DESTINATION='platform=iOS Simulator,name=iPad Pro (12.9-inch) (3rd generation)'
  - DESTINATION='platform=iOS Simulator,name=iPhone 5'
  - DESTINATION='platform=iOS Simulator,name=iPhone 5s'
  - DESTINATION='platform=iOS Simulator,name=iPhone 6'
  - DESTINATION='platform=iOS Simulator,name=iPhone 6 Plus'
  - DESTINATION='platform=iOS Simulator,OS=12.4,name=iPhone 6s'
  - DESTINATION='platform=iOS Simulator,OS=12.4,name=iPhone 6s Plus'
  - DESTINATION='platform=iOS Simulator,OS=12.4,name=iPhone SE'
  - DESTINATION='platform=iOS Simulator,OS=12.4,name=iPhone 7'
  - DESTINATION='platform=iOS Simulator,OS=12.4,name=iPhone 7 Plus'

script:
  - set -o pipefail && xcodebuild -project SMDatePicker.xcodeproj -scheme SMDatePicker -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO clean | xcpretty
